#!/usr/bin/env bash
# Apply the local gpui-pre-linux backdrop-blur patch.
#
# Why: gpui 0.3.3 binds only KDE's `org_kde_kwin_blur`. The cross-compositor
# `ext-background-effect-v1` protocol — the one KWin 6.7+, Mutter 51+ (GNOME 51)
# and Hyprland speak — is never requested, and an app cannot ask for it itself
# because gpui never hands out the window's `wl_surface`. So the binding has to
# live inside the backend crate.
#
# How: the crate is copied out of the cargo registry (or downloaded from
# static.crates.io) to `vendor/gpui-pre-linux`, the patch is applied on top, and
# a generated `.cargo/config.toml` points cargo at that copy through
# `[patch.crates-io]`. Nothing in git is a fork of gpui, and a checkout that has
# never run this script still builds — it just gets stock gpui, where the glass
# backdrop stays a translucent tint.
#
# Usage:
#   ./scripts/patch-gpui.sh              # materialise vendor/ + .cargo/config.toml
#   ./scripts/patch-gpui.sh --check      # dry run: does the patch still apply?
#   ./scripts/patch-gpui.sh 0.3.4        # patch a specific crate version
#
# When gpui is bumped: bump the pin, run this again. If a hunk has drifted the
# script says which anchor moved and leaves `vendor/` untouched, so a build can
# never quietly lose the blur. To refresh the patch itself, diff the patched
# `vendor/gpui-pre-linux` against a pristine copy of the same crate.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GPUI_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ROOT="$(cd "${GPUI_DIR}/.." && pwd)"

CRATE_NAME="gpui-pre-linux"
PATCH_FILE="${GPUI_DIR}/patches/${CRATE_NAME}-background-effect.patch"
VENDOR_DIR="${GPUI_DIR}/vendor/${CRATE_NAME}"
CONFIG_FILE="${ROOT}/.cargo/config.toml"
WORK_DIR="${GPUI_DIR}/target/patch-gpui"
CONFIG_MARKER="Generated by desktop-gpui/scripts/patch-gpui.sh"

log() { printf '\033[0;36m[patch-gpui]\033[0m %s\n' "$1"; }
warn() { printf '\033[0;33m[patch-gpui] %s\033[0m\n' "$1" >&2; }
fail() { printf '\033[0;31m[patch-gpui] %s\033[0m\n' "$1" >&2; exit 1; }

CHECK_ONLY=0
REQUESTED_VERSION=""
for arg in "$@"; do
    case "$arg" in
        --check) CHECK_ONLY=1 ;;
        -h|--help)
            sed -n '2,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        -*) fail "unknown option: $arg" ;;
        *) REQUESTED_VERSION="$arg" ;;
    esac
done

[[ -f "$PATCH_FILE" ]] || fail "patch not found: $PATCH_FILE"

resolve_version() {
    if [[ -n "$REQUESTED_VERSION" ]]; then
        printf '%s\n' "$REQUESTED_VERSION"
        return
    fi
    if [[ -n "${PATCH_GPUI_VERSION:-}" ]]; then
        printf '%s\n' "$PATCH_GPUI_VERSION"
        return
    fi
    [[ -f "${GPUI_DIR}/Cargo.lock" ]] || fail "no Cargo.lock; pass the version explicitly"
    awk -v crate="\"${CRATE_NAME}\"" '
        /^\[\[package\]\]/ { name = ""; version = "" }
        /^name = / { name = $3 }
        /^version = / { version = $3 }
        name == crate && version != "" { gsub(/"/, "", version); print version; exit }
    ' "${GPUI_DIR}/Cargo.lock"
}

find_cached_source() {
    local version="$1" dir
    for dir in "${CARGO_HOME:-$HOME/.cargo}/registry/src"/*/"${CRATE_NAME}-${version}"; do
        if [[ -d "$dir" ]]; then
            printf '%s\n' "$dir"
            return 0
        fi
    done
    return 1
}

download_source() {
    local version="$1" archive url extract_dir
    archive="${WORK_DIR}/${CRATE_NAME}-${version}.crate"
    extract_dir="${WORK_DIR}/download"
    url="https://static.crates.io/crates/${CRATE_NAME}/${CRATE_NAME}-${version}.crate"
    mkdir -p "$extract_dir"
    [[ -f "$archive" ]] || {
        log "Downloading ${CRATE_NAME}-${version}.crate"
        if command -v curl >/dev/null; then
            curl -fsSL --retry 3 -o "$archive" "$url" || fail "download failed: $url"
        elif command -v wget >/dev/null; then
            wget -q -O "$archive" "$url" || fail "download failed: $url"
        else
            fail "need curl or wget to download $url"
        fi
    }
    tar -xzf "$archive" -C "$extract_dir" || fail "could not extract $archive"
    printf '%s\n' "${extract_dir}/${CRATE_NAME}-${version}"
}

materialize() {
    local source="$1" dest="$2" extra
    rm -rf "$dest"
    mkdir -p "$dest"
    [[ -d "$source/src" ]] || fail "not a ${CRATE_NAME} source tree: $source"
    cp -R "$source/src" "$dest/src"
    for extra in Cargo.toml Cargo.toml.orig LICENSE-APACHE LICENSE-MIT README.md; do
        if [[ -f "$source/$extra" ]]; then
            cp "$source/$extra" "$dest/$extra"
        fi
    done
}

apply_patch() {
    local dir="$1"
    (
        cd "$dir"
        # `git apply` inside a work tree silently ignores paths that do not sit
        # under the repository root, which is exactly our case, so it is forced
        # into its no-repository mode. GNU patch is the fuzzy fallback for the
        # day a gpui bump moves an anchor slightly; the marker check below is
        # what decides whether either of them actually worked.
        if command -v git >/dev/null \
            && GIT_DIR=/dev/null GIT_WORK_TREE=/dev/null git apply -p1 --whitespace=nowarn "$PATCH_FILE" 2>/dev/null; then
            return 0
        fi
        if command -v patch >/dev/null \
            && patch -p1 --forward --fuzz=3 -s <"$PATCH_FILE" >/dev/null 2>&1; then
            return 0
        fi
        return 1
    )
}

verify_patch() {
    local dir="$1" missing="" marker
    local client="${dir}/src/linux/wayland/client.rs"
    local window="${dir}/src/linux/wayland/window.rs"

    check_marker() {
        grep -qF "$2" "$1" || missing="${missing}  $1 :: $2"$'\n'
    }
    check_marker "$client" "use wayland_protocols::ext::background_effect::v1::client"
    check_marker "$client" "background_effect_manager: globals.bind"
    check_marker "$client" "ignore ext_background_effect_surface_v1::ExtBackgroundEffectSurfaceV1"
    check_marker "$window" "get_background_effect(&state.surface"
    check_marker "$window" "set_blur_region(Some(&blur_region))"

    if [[ -n "$missing" ]]; then
        printf '%s' "$missing" >&2
        return 1
    fi
    return 0
}

write_config() {
    local relative="$1"
    if [[ -f "$CONFIG_FILE" ]] && ! grep -qF "$CONFIG_MARKER" "$CONFIG_FILE"; then
        fail "$CONFIG_FILE exists and was not written by this script; add the [patch.crates-io] entry by hand"
    fi
    mkdir -p "$(dirname "$CONFIG_FILE")"
    cat >"$CONFIG_FILE" <<EOF
# ${CONFIG_MARKER} — do not commit.
# Points cargo at the locally patched ${CRATE_NAME} that binds
# ext-background-effect-v1, so \`WindowBackgroundAppearance::Blurred\` reaches
# GNOME 51+, KWin 6.7+ and Hyprland. Delete this file for stock gpui.
[patch.crates-io]
${CRATE_NAME} = { path = "${relative}" }
EOF
}

VERSION="$(resolve_version)"
[[ -n "$VERSION" ]] || fail "could not determine ${CRATE_NAME} version; pass it explicitly"

SOURCE="$(find_cached_source "$VERSION" || true)"
if [[ -n "$SOURCE" ]]; then
    log "Using cached source ${SOURCE}"
else
    SOURCE="$(download_source "$VERSION")"
fi

TARGET_DIR="$VENDOR_DIR"
if [[ "$CHECK_ONLY" == "1" ]]; then
    TARGET_DIR="${WORK_DIR}/check"
    log "Checking ${CRATE_NAME} ${VERSION} against $(basename "$PATCH_FILE")"
else
    log "Patching ${CRATE_NAME} ${VERSION} into vendor/${CRATE_NAME}"
fi

materialize "$SOURCE" "$TARGET_DIR"

if ! apply_patch "$TARGET_DIR"; then
    rm -rf "$TARGET_DIR"
    fail "patch did not apply; refresh ${PATCH_FILE#"$ROOT"/} against ${CRATE_NAME} ${VERSION}"
fi

if ! verify_patch "$TARGET_DIR"; then
    rm -rf "$TARGET_DIR"
    fail "patch applied but the expected code is missing (see anchors above); refresh the patch"
fi

if [[ "$CHECK_ONLY" == "1" ]]; then
    rm -rf "${WORK_DIR}/check"
    log "OK: ${CRATE_NAME} ${VERSION} still accepts the patch"
    exit 0
fi

# Cargo resolves a path in a config `[patch]` table relative to the directory
# that holds `.cargo`, not to the file itself.
RELATIVE="${GPUI_DIR#"$ROOT"/}/vendor/${CRATE_NAME}"
write_config "$RELATIVE"
log "vendor/${CRATE_NAME} ready; .cargo/config.toml points cargo at it"
log "Blur backdrop reaches GNOME 51+, KWin 6.7+ and Hyprland once the compositor supports it"
warn "while this patch is active cargo drops the source+checksum lines of the ${CRATE_NAME} entry in Cargo.lock; leave that local change uncommitted"
