//! Theme management and multi-theme presets mirroring fe/ web client.

use gpui::{rgb, App, Rgba};
use gpui_component::{Theme, ThemeMode};
use webterm_settings::Theme as SettingsTheme;

/// Complete theme color palette mirroring web client ThemePreset.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ThemePreset {
    pub id: &'static str,
    pub label: &'static str,
    pub is_dark: bool,
    pub background: u32,
    pub foreground: u32,
    pub card: u32,
    pub card_foreground: u32,
    pub primary: u32,
    pub primary_foreground: u32,
    pub secondary: u32,
    pub secondary_foreground: u32,
    pub muted: u32,
    pub muted_foreground: u32,
    pub accent: u32,
    pub accent_foreground: u32,
    pub destructive: u32,
    pub border: u32,
}

impl ThemePreset {
    pub fn bg(&self) -> Rgba { rgb(self.background) }
    pub fn fg(&self) -> Rgba { rgb(self.foreground) }
    pub fn card_bg(&self) -> Rgba { rgb(self.card) }
    pub fn card_fg(&self) -> Rgba { rgb(self.card_foreground) }
    pub fn primary(&self) -> Rgba { rgb(self.primary) }
    pub fn primary_fg(&self) -> Rgba { rgb(self.primary_foreground) }
    pub fn secondary(&self) -> Rgba { rgb(self.secondary) }
    pub fn secondary_fg(&self) -> Rgba { rgb(self.secondary_foreground) }
    pub fn muted(&self) -> Rgba { rgb(self.muted) }
    pub fn muted_fg(&self) -> Rgba { rgb(self.muted_foreground) }
    pub fn accent(&self) -> Rgba { rgb(self.accent) }
    pub fn accent_fg(&self) -> Rgba { rgb(self.accent_foreground) }
    pub fn destructive(&self) -> Rgba { rgb(self.destructive) }
    pub fn border(&self) -> Rgba { rgb(self.border) }
}

/// Comprehensive list of theme presets ported from fe/src/features/settings/data/themes.ts
pub const THEME_PRESETS: &[ThemePreset] = &[
    // Defaults & Monochromes
    ThemePreset {
        id: "default-dark",
        label: "Default Dark",
        is_dark: true,
        background: 0x1e1e1e,
        foreground: 0xd4d4d4,
        card: 0x1e1e1e,
        card_foreground: 0xd4d4d4,
        primary: 0x00df9a,
        primary_foreground: 0x000000,
        secondary: 0x2d2d2d,
        secondary_foreground: 0xd4d4d4,
        muted: 0x2d2d2d,
        muted_foreground: 0x808080,
        accent: 0x2d2d2d,
        accent_foreground: 0xd4d4d4,
        destructive: 0x7f1d1d,
        border: 0x3c3c3c,
    },
    ThemePreset {
        id: "default-light",
        label: "Default Light",
        is_dark: false,
        background: 0xfafafa,
        foreground: 0x383a42,
        card: 0xffffff,
        card_foreground: 0x383a42,
        primary: 0x059669,
        primary_foreground: 0xffffff,
        secondary: 0xf0f0f0,
        secondary_foreground: 0x383a42,
        muted: 0xf0f0f0,
        muted_foreground: 0xa0a1a7,
        accent: 0xf0f0f0,
        accent_foreground: 0x383a42,
        destructive: 0xef4444,
        border: 0xdbdbdc,
    },
    ThemePreset {
        id: "mono-dark",
        label: "Monochrome Dark",
        is_dark: true,
        background: 0x09090b,
        foreground: 0xfafafa,
        card: 0x18181b,
        card_foreground: 0xfafafa,
        primary: 0x00df9a,
        primary_foreground: 0x000000,
        secondary: 0x27272a,
        secondary_foreground: 0xfafafa,
        muted: 0x1b1b1d,
        muted_foreground: 0xa1a1aa,
        accent: 0x3f3f46,
        accent_foreground: 0xfafafa,
        destructive: 0x7f1d1d,
        border: 0x27272a,
    },
    ThemePreset {
        id: "mono-light",
        label: "Monochrome Light",
        is_dark: false,
        background: 0xfafafa,
        foreground: 0x09090b,
        card: 0xffffff,
        card_foreground: 0x09090b,
        primary: 0x059669,
        primary_foreground: 0xffffff,
        secondary: 0xf4f4f5,
        secondary_foreground: 0x09090b,
        muted: 0xededed,
        muted_foreground: 0x71717a,
        accent: 0xf4f4f5,
        accent_foreground: 0x09090b,
        destructive: 0xef4444,
        border: 0xe4e4e7,
    },

    // Popular Developer Favorites
    ThemePreset {
        id: "tokyo-night-dark",
        label: "Tokyo Night",
        is_dark: true,
        background: 0x1a1b26,
        foreground: 0xc0caf5,
        card: 0x24283b,
        card_foreground: 0xc0caf5,
        primary: 0x7aa2f7,
        primary_foreground: 0x1a1b26,
        secondary: 0x24283b,
        secondary_foreground: 0xc0caf5,
        muted: 0x2c2d38,
        muted_foreground: 0x565f89,
        accent: 0xbb9af7,
        accent_foreground: 0x1a1b26,
        destructive: 0xf7768e,
        border: 0x292e42,
    },
    ThemePreset {
        id: "catppuccin-dark",
        label: "Catppuccin Mocha",
        is_dark: true,
        background: 0x1e1e2e,
        foreground: 0xcdd6f4,
        card: 0x313244,
        card_foreground: 0xcdd6f4,
        primary: 0xcba6f7,
        primary_foreground: 0x1e1e2e,
        secondary: 0x313244,
        secondary_foreground: 0xcdd6f4,
        muted: 0x303040,
        muted_foreground: 0x6c7086,
        accent: 0x89b4fa,
        accent_foreground: 0x1e1e2e,
        destructive: 0xf38ba8,
        border: 0x45475a,
    },
    ThemePreset {
        id: "dracula-dark",
        label: "Dracula",
        is_dark: true,
        background: 0x282a36,
        foreground: 0xf8f8f2,
        card: 0x343746,
        card_foreground: 0xf8f8f2,
        primary: 0xbd93f9,
        primary_foreground: 0x282a36,
        secondary: 0x343746,
        secondary_foreground: 0xf8f8f2,
        muted: 0x3a3c48,
        muted_foreground: 0x6272a4,
        accent: 0xff79c6,
        accent_foreground: 0x282a36,
        destructive: 0xff5555,
        border: 0x44475a,
    },
    ThemePreset {
        id: "monokai-dark",
        label: "Monokai",
        is_dark: true,
        background: 0x272822,
        foreground: 0xf8f8f2,
        card: 0x3d3e34,
        card_foreground: 0xf8f8f2,
        primary: 0xa6e22e,
        primary_foreground: 0x272822,
        secondary: 0x3d3e34,
        secondary_foreground: 0xf8f8f2,
        muted: 0x393a34,
        muted_foreground: 0x75715e,
        accent: 0xf92672,
        accent_foreground: 0xf8f8f2,
        destructive: 0xf92672,
        border: 0x49483e,
    },
    ThemePreset {
        id: "nord-dark",
        label: "Nord",
        is_dark: true,
        background: 0x2e3440,
        foreground: 0xeceff4,
        card: 0x3b4252,
        card_foreground: 0xeceff4,
        primary: 0x88c0d0,
        primary_foreground: 0x2e3440,
        secondary: 0x434c5e,
        secondary_foreground: 0xeceff4,
        muted: 0x404652,
        muted_foreground: 0xd8dee9,
        accent: 0x5e81ac,
        accent_foreground: 0xeceff4,
        destructive: 0xbf616a,
        border: 0x4c566a,
    },
    ThemePreset {
        id: "nord-light",
        label: "Nord Light",
        is_dark: false,
        background: 0xeceff4,
        foreground: 0x2e3440,
        card: 0xffffff,
        card_foreground: 0x2e3440,
        primary: 0x5e81ac,
        primary_foreground: 0xffffff,
        secondary: 0xe5e9f0,
        secondary_foreground: 0x2e3440,
        muted: 0xdfe2e7,
        muted_foreground: 0x4c566a,
        accent: 0xd8dee9,
        accent_foreground: 0x2e3440,
        destructive: 0xbf616a,
        border: 0xd8dee9,
    },
    ThemePreset {
        id: "gruvbox-dark",
        label: "Gruvbox",
        is_dark: true,
        background: 0x282828,
        foreground: 0xebdbb2,
        card: 0x3c3836,
        card_foreground: 0xebdbb2,
        primary: 0xfabd2f,
        primary_foreground: 0x282828,
        secondary: 0x3c3836,
        secondary_foreground: 0xebdbb2,
        muted: 0x3a3a3a,
        muted_foreground: 0xa89984,
        accent: 0x83a598,
        accent_foreground: 0x282828,
        destructive: 0xfb4934,
        border: 0x504945,
    },
    ThemePreset {
        id: "gruvbox-light",
        label: "Gruvbox Light",
        is_dark: false,
        background: 0xfbf1c7,
        foreground: 0x3c3836,
        card: 0xebdbb2,
        card_foreground: 0x3c3836,
        primary: 0xd79921,
        primary_foreground: 0xfbf1c7,
        secondary: 0xebdbb2,
        secondary_foreground: 0x3c3836,
        muted: 0xeee4ba,
        muted_foreground: 0x7c6f64,
        accent: 0x076678,
        accent_foreground: 0xfbf1c7,
        destructive: 0xcc241d,
        border: 0xd5c4a1,
    },
    ThemePreset {
        id: "github-dark",
        label: "GitHub Dark",
        is_dark: true,
        background: 0x0d1117,
        foreground: 0xc9d1d9,
        card: 0x161b22,
        card_foreground: 0xc9d1d9,
        primary: 0x58a6ff,
        primary_foreground: 0x0d1117,
        secondary: 0x161b22,
        secondary_foreground: 0xc9d1d9,
        muted: 0x1f2329,
        muted_foreground: 0x8b949e,
        accent: 0xf78166,
        accent_foreground: 0x0d1117,
        destructive: 0xf85149,
        border: 0x30363d,
    },
    ThemePreset {
        id: "github-light",
        label: "GitHub Light",
        is_dark: false,
        background: 0xffffff,
        foreground: 0x24292f,
        card: 0xf6f8fa,
        card_foreground: 0x24292f,
        primary: 0x0969da,
        primary_foreground: 0xffffff,
        secondary: 0xf6f8fa,
        secondary_foreground: 0x24292f,
        muted: 0xf2f2f2,
        muted_foreground: 0x656d76,
        accent: 0xcf222e,
        accent_foreground: 0xffffff,
        destructive: 0xcf222e,
        border: 0xd0d7de,
    },
    ThemePreset {
        id: "one-dark",
        label: "One Dark",
        is_dark: true,
        background: 0x282c34,
        foreground: 0xabb2bf,
        card: 0x353a44,
        card_foreground: 0xabb2bf,
        primary: 0x61afef,
        primary_foreground: 0x282c34,
        secondary: 0x353a44,
        secondary_foreground: 0xabb2bf,
        muted: 0x3a3e46,
        muted_foreground: 0x5c6370,
        accent: 0xe5c07b,
        accent_foreground: 0x282c34,
        destructive: 0xe06c75,
        border: 0x3e4451,
    },
    ThemePreset {
        id: "one-light",
        label: "One Light",
        is_dark: false,
        background: 0xfafafa,
        foreground: 0x383a42,
        card: 0xffffff,
        card_foreground: 0x383a42,
        primary: 0x4078f2,
        primary_foreground: 0xffffff,
        secondary: 0xf0f0f0,
        secondary_foreground: 0x383a42,
        muted: 0xededed,
        muted_foreground: 0xa0a1a7,
        accent: 0xe45649,
        accent_foreground: 0xffffff,
        destructive: 0xca1243,
        border: 0xdbdbdc,
    },
    ThemePreset {
        id: "solarized-dark",
        label: "Solarized Dark",
        is_dark: true,
        background: 0x002b36,
        foreground: 0x839496,
        card: 0x073642,
        card_foreground: 0x839496,
        primary: 0x268bd2,
        primary_foreground: 0xfdf6e3,
        secondary: 0x073642,
        secondary_foreground: 0x839496,
        muted: 0x123d48,
        muted_foreground: 0x586e75,
        accent: 0x2aa198,
        accent_foreground: 0xfdf6e3,
        destructive: 0xdc322f,
        border: 0x586e75,
    },
    ThemePreset {
        id: "solarized-light",
        label: "Solarized Light",
        is_dark: false,
        background: 0xfdf6e3,
        foreground: 0x657b83,
        card: 0xeee8d5,
        card_foreground: 0x657b83,
        primary: 0x268bd2,
        primary_foreground: 0xfdf6e3,
        secondary: 0xeee8d5,
        secondary_foreground: 0x657b83,
        muted: 0xf0e9d6,
        muted_foreground: 0x93a1a1,
        accent: 0x2aa198,
        accent_foreground: 0xfdf6e3,
        destructive: 0xdc322f,
        border: 0xd3cbb4,
    },
    ThemePreset {
        id: "rose-pine-dark",
        label: "Rosé Pine",
        is_dark: true,
        background: 0x191724,
        foreground: 0xe0def4,
        card: 0x26233a,
        card_foreground: 0xe0def4,
        primary: 0xebbcba,
        primary_foreground: 0x191724,
        secondary: 0x26233a,
        secondary_foreground: 0xe0def4,
        muted: 0x2b2936,
        muted_foreground: 0x908caa,
        accent: 0x31748f,
        accent_foreground: 0x191724,
        destructive: 0xeb6f92,
        border: 0x312e42,
    },
    ThemePreset {
        id: "cyberpunk-dark",
        label: "Cyberpunk",
        is_dark: true,
        background: 0x0d0a1a,
        foreground: 0xffffff,
        card: 0x1a1533,
        card_foreground: 0xffffff,
        primary: 0xff007f,
        primary_foreground: 0xffffff,
        secondary: 0x1a1533,
        secondary_foreground: 0xffffff,
        muted: 0x1f1c2c,
        muted_foreground: 0x8880b8,
        accent: 0x00f0ff,
        accent_foreground: 0x0d0a1a,
        destructive: 0xff3333,
        border: 0x332d66,
    },
    ThemePreset {
        id: "obsidian-dark",
        label: "Obsidian",
        is_dark: true,
        background: 0x0c0c0f,
        foreground: 0xebebeb,
        card: 0x18181f,
        card_foreground: 0xebebeb,
        primary: 0x8b5cf6,
        primary_foreground: 0xffffff,
        secondary: 0x18181f,
        secondary_foreground: 0xebebeb,
        muted: 0x1e1e21,
        muted_foreground: 0x6b6b7b,
        accent: 0x10b981,
        accent_foreground: 0x0c0c0f,
        destructive: 0xef4444,
        border: 0x2a2a33,
    },
    ThemePreset {
        id: "synthwave-dark",
        label: "Synthwave '84",
        is_dark: true,
        background: 0x262335,
        foreground: 0xe0e0e0,
        card: 0x34294f,
        card_foreground: 0xe0e0e0,
        primary: 0xf92aad,
        primary_foreground: 0xffffff,
        secondary: 0x34294f,
        secondary_foreground: 0xe0e0e0,
        muted: 0x383547,
        muted_foreground: 0x848bbd,
        accent: 0x36f9f6,
        accent_foreground: 0x262335,
        destructive: 0xff8b39,
        border: 0x495495,
    },
    ThemePreset {
        id: "midnight-dark",
        label: "Midnight Indigo",
        is_dark: true,
        background: 0x090b1e,
        foreground: 0xffffff,
        card: 0x131840,
        card_foreground: 0xffffff,
        primary: 0x6366f1,
        primary_foreground: 0xffffff,
        secondary: 0x131840,
        secondary_foreground: 0xffffff,
        muted: 0x1b1d30,
        muted_foreground: 0xa5b4fc,
        accent: 0x3730a3,
        accent_foreground: 0xffffff,
        destructive: 0x7f1d1d,
        border: 0x232b5e,
    },
    ThemePreset {
        id: "midnight-light",
        label: "Midnight Light",
        is_dark: false,
        background: 0xeef2ff,
        foreground: 0x0f172a,
        card: 0xffffff,
        card_foreground: 0x0f172a,
        primary: 0x4f46e5,
        primary_foreground: 0xffffff,
        secondary: 0xe0e7ff,
        secondary_foreground: 0x0f172a,
        muted: 0xe1e5f2,
        muted_foreground: 0x6366f1,
        accent: 0xe0e7ff,
        accent_foreground: 0x0f172a,
        destructive: 0xef4444,
        border: 0xc7d2fe,
    },

    // Rich Color Schemes
    ThemePreset {
        id: "mint-dark",
        label: "Mint",
        is_dark: true,
        background: 0x022c22,
        foreground: 0xffffff,
        card: 0x064e3b,
        card_foreground: 0xffffff,
        primary: 0x34d399,
        primary_foreground: 0x022c22,
        secondary: 0x064e3b,
        secondary_foreground: 0xffffff,
        muted: 0x143e34,
        muted_foreground: 0x6ee7b7,
        accent: 0x047857,
        accent_foreground: 0xffffff,
        destructive: 0x7f1d1d,
        border: 0x065f46,
    },
    ThemePreset {
        id: "mint-light",
        label: "Mint Light",
        is_dark: false,
        background: 0xf0fdfa,
        foreground: 0x0f172a,
        card: 0xffffff,
        card_foreground: 0x0f172a,
        primary: 0x0d9488,
        primary_foreground: 0xffffff,
        secondary: 0xccfbf1,
        secondary_foreground: 0x0f172a,
        muted: 0xe3f0ed,
        muted_foreground: 0x5eead4,
        accent: 0xccfbf1,
        accent_foreground: 0x0f172a,
        destructive: 0xef4444,
        border: 0x99f6e4,
    },
    ThemePreset {
        id: "ocean-dark",
        label: "Ocean",
        is_dark: true,
        background: 0x0c1929,
        foreground: 0xffffff,
        card: 0x162940,
        card_foreground: 0xffffff,
        primary: 0x2563eb,
        primary_foreground: 0xffffff,
        secondary: 0x162940,
        secondary_foreground: 0xffffff,
        muted: 0x1e2b3b,
        muted_foreground: 0x94a3b8,
        accent: 0x1e3a5f,
        accent_foreground: 0xffffff,
        destructive: 0x7f1d1d,
        border: 0x274768,
    },
    ThemePreset {
        id: "ocean-light",
        label: "Ocean Light",
        is_dark: false,
        background: 0xf0f9ff,
        foreground: 0x0f172a,
        card: 0xffffff,
        card_foreground: 0x0f172a,
        primary: 0x2563eb,
        primary_foreground: 0xffffff,
        secondary: 0xeff6ff,
        secondary_foreground: 0x0f172a,
        muted: 0xe3ecf2,
        muted_foreground: 0x64748b,
        accent: 0xeff6ff,
        accent_foreground: 0x0f172a,
        destructive: 0xef4444,
        border: 0xbfdbfe,
    },
    ThemePreset {
        id: "forest-dark",
        label: "Forest",
        is_dark: true,
        background: 0x0c1f17,
        foreground: 0xffffff,
        card: 0x173025,
        card_foreground: 0xffffff,
        primary: 0x059669,
        primary_foreground: 0xffffff,
        secondary: 0x173025,
        secondary_foreground: 0xffffff,
        muted: 0x1e3129,
        muted_foreground: 0x94a3b8,
        accent: 0x064e3b,
        accent_foreground: 0xffffff,
        destructive: 0x7f1d1d,
        border: 0x1f4a32,
    },
    ThemePreset {
        id: "forest-light",
        label: "Forest Light",
        is_dark: false,
        background: 0xf0fdf4,
        foreground: 0x0f172a,
        card: 0xffffff,
        card_foreground: 0x0f172a,
        primary: 0x059669,
        primary_foreground: 0xffffff,
        secondary: 0xecfdf5,
        secondary_foreground: 0x0f172a,
        muted: 0xe3f0e7,
        muted_foreground: 0x64748b,
        accent: 0xecfdf5,
        accent_foreground: 0x0f172a,
        destructive: 0xef4444,
        border: 0xa7f3d0,
    },
    ThemePreset {
        id: "lavender-dark",
        label: "Lavender",
        is_dark: true,
        background: 0x131127,
        foreground: 0xffffff,
        card: 0x1f1b3d,
        card_foreground: 0xffffff,
        primary: 0x7c3aed,
        primary_foreground: 0xffffff,
        secondary: 0x1f1b3d,
        secondary_foreground: 0xffffff,
        muted: 0x252339,
        muted_foreground: 0x94a3b8,
        accent: 0x4c1d95,
        accent_foreground: 0xffffff,
        destructive: 0x7f1d1d,
        border: 0x362d5c,
    },
    ThemePreset {
        id: "lavender-light",
        label: "Lavender Light",
        is_dark: false,
        background: 0xfaf5ff,
        foreground: 0x0f172a,
        card: 0xffffff,
        card_foreground: 0x0f172a,
        primary: 0x7c3aed,
        primary_foreground: 0xffffff,
        secondary: 0xf5f3ff,
        secondary_foreground: 0x0f172a,
        muted: 0xede8f2,
        muted_foreground: 0x64748b,
        accent: 0xf5f3ff,
        accent_foreground: 0x0f172a,
        destructive: 0xef4444,
        border: 0xc4b5fd,
    },
    ThemePreset {
        id: "cherry-dark",
        label: "Cherry",
        is_dark: true,
        background: 0x1a0f14,
        foreground: 0xffffff,
        card: 0x271a22,
        card_foreground: 0xffffff,
        primary: 0xe11d48,
        primary_foreground: 0xffffff,
        secondary: 0x271a22,
        secondary_foreground: 0xffffff,
        muted: 0x2c2126,
        muted_foreground: 0x94a3b8,
        accent: 0x4c0519,
        accent_foreground: 0xffffff,
        destructive: 0x7f1d1d,
        border: 0x442838,
    },
    ThemePreset {
        id: "cherry-light",
        label: "Cherry Light",
        is_dark: false,
        background: 0xfff5f5,
        foreground: 0x0f172a,
        card: 0xffffff,
        card_foreground: 0x0f172a,
        primary: 0xe11d48,
        primary_foreground: 0xffffff,
        secondary: 0xfff1f2,
        secondary_foreground: 0x0f172a,
        muted: 0xf2e8e8,
        muted_foreground: 0x64748b,
        accent: 0xfff1f2,
        accent_foreground: 0x0f172a,
        destructive: 0xef4444,
        border: 0xfecdd3,
    },
    ThemePreset {
        id: "sunset-dark",
        label: "Sunset",
        is_dark: true,
        background: 0x19140d,
        foreground: 0xffffff,
        card: 0x262016,
        card_foreground: 0xffffff,
        primary: 0xb45309,
        primary_foreground: 0xffffff,
        secondary: 0x262016,
        secondary_foreground: 0xffffff,
        muted: 0x2b261f,
        muted_foreground: 0x94a3b8,
        accent: 0x78350f,
        accent_foreground: 0xffffff,
        destructive: 0x7f1d1d,
        border: 0x403828,
    },
    ThemePreset {
        id: "sunset-light",
        label: "Sunset Light",
        is_dark: false,
        background: 0xfff7ed,
        foreground: 0x0f172a,
        card: 0xffffff,
        card_foreground: 0x0f172a,
        primary: 0xd97706,
        primary_foreground: 0xffffff,
        secondary: 0xfffbeb,
        secondary_foreground: 0x0f172a,
        muted: 0xf2eae0,
        muted_foreground: 0x64748b,
        accent: 0xfffbeb,
        accent_foreground: 0x0f172a,
        destructive: 0xef4444,
        border: 0xfde68a,
    },
    ThemePreset {
        id: "plum-dark",
        label: "Plum",
        is_dark: true,
        background: 0x1a1423,
        foreground: 0xffffff,
        card: 0x261f33,
        card_foreground: 0xffffff,
        primary: 0xc084fc,
        primary_foreground: 0x1a1423,
        secondary: 0x261f33,
        secondary_foreground: 0xffffff,
        muted: 0x2c2635,
        muted_foreground: 0xa491c1,
        accent: 0x6b21a8,
        accent_foreground: 0xffffff,
        destructive: 0xb91c1c,
        border: 0x3b2e4f,
    },
    ThemePreset {
        id: "teal-dark",
        label: "Teal",
        is_dark: true,
        background: 0x081a17,
        foreground: 0xffffff,
        card: 0x0f2d26,
        card_foreground: 0xffffff,
        primary: 0x14b8a6,
        primary_foreground: 0x081a17,
        secondary: 0x0f2d26,
        secondary_foreground: 0xffffff,
        muted: 0x1a2c29,
        muted_foreground: 0x5eead4,
        accent: 0x0f766e,
        accent_foreground: 0xffffff,
        destructive: 0xb91c1c,
        border: 0x1c4037,
    },
    ThemePreset {
        id: "frost-dark",
        label: "Frost",
        is_dark: true,
        background: 0x0f1923,
        foreground: 0xffffff,
        card: 0x1a2b3f,
        card_foreground: 0xffffff,
        primary: 0x7dd3fc,
        primary_foreground: 0x0f1923,
        secondary: 0x1a2b3f,
        secondary_foreground: 0xffffff,
        muted: 0x212b35,
        muted_foreground: 0x8bb8d6,
        accent: 0x0c4a6e,
        accent_foreground: 0xffffff,
        destructive: 0xb91c1c,
        border: 0x253e57,
    },
];

/// Find a ThemePreset by its ID. Falls back to "default-dark" if not found.
pub fn find_theme_preset(id: &str) -> &'static ThemePreset {
    THEME_PRESETS
        .iter()
        .find(|t| t.id == id)
        .unwrap_or(&THEME_PRESETS[0])
}

/// Apply the given settings theme to the GPUI application context.
pub fn apply_theme(theme: SettingsTheme, cx: &mut App) {
    match theme {
        SettingsTheme::Light => {
            Theme::change(ThemeMode::Light, None, cx);
        }
        SettingsTheme::Dark | SettingsTheme::System => {
            Theme::change(ThemeMode::Dark, None, cx);
        }
    }
}

/// Flip between Dark and Light themes.
pub fn toggle_theme(current: SettingsTheme) -> SettingsTheme {
    match current {
        SettingsTheme::Light => SettingsTheme::Dark,
        SettingsTheme::Dark | SettingsTheme::System => SettingsTheme::Light,
    }
}
